name = "galai"
main = "worker.js"
compatibility_date = "2024-12-01"

[vars]

[[r2_buckets]]
binding = "SITE_BUCKET"
bucket_name = "galai-site"

[routes]
pattern = "galai.dpdns.org/*"
zone_name = "dpdns.org"
